### ISSUE TITLE
Navigator data pass is not working

### ISSUE THREAD

**Issue by ambatidilip** [OnsenUI/OnsenUI-dist#2]
I updated from 2.0.0 to 2.0.5. When i did, i am transferring some data from first page to second page. While fetching data on second page it is coming as null (Empty).  - I am using Angular JS 1

**Comment by erikcw** [comment]
I just upgraded to `2.2.4` and spent the last couple of hours banging my head against the wall with this one also.

**Comment by frandiox** [comment]
@ambatidilip @erikcw There are other issues closed about this. You can use page lifecycle events to ensure the data object is there. I just updated the [tutorial](http://tutorial.onsen.io/?framework=angular1&category=reference&module=navigator) to show an example.
